/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.glavna;

import forme.kompanija.FrmPrikazKompanija;
import forme.kompanija.FrmPrikazKompanijaModel;
import forme.kompanija.FrmUnosKompanije;
import forme.racun.FrmUnosRacuna;
import java.awt.BorderLayout;
import javax.swing.JDialog;

/**
 *
 * @author Milica
 */
public class FrmGlavna extends javax.swing.JFrame {

    /**
     * Creates new form FrmGlavna
     */
    public FrmGlavna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmbGlavniMeni = new javax.swing.JMenuBar();
        jmRadSaKompanijama = new javax.swing.JMenu();
        jmiUnosKompanije = new javax.swing.JMenuItem();
        jmiPrikazKompanija = new javax.swing.JMenuItem();
        jmiPrikazKompanijaModel = new javax.swing.JMenuItem();
        jmRadSaMestima = new javax.swing.JMenu();
        jmRadSaRacunima = new javax.swing.JMenu();
        jmiUnosRacuna = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[FON] Program za rad sa kompanijama");

        jmRadSaKompanijama.setText("Rad sa kompanijama");

        jmiUnosKompanije.setText("Unos kompanije");
        jmiUnosKompanije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosKompanijeActionPerformed(evt);
            }
        });
        jmRadSaKompanijama.add(jmiUnosKompanije);

        jmiPrikazKompanija.setText("Prikaz kompanija");
        jmiPrikazKompanija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrikazKompanijaActionPerformed(evt);
            }
        });
        jmRadSaKompanijama.add(jmiPrikazKompanija);

        jmiPrikazKompanijaModel.setText("Prikaz kompanija - model");
        jmiPrikazKompanijaModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrikazKompanijaModelActionPerformed(evt);
            }
        });
        jmRadSaKompanijama.add(jmiPrikazKompanijaModel);

        jmbGlavniMeni.add(jmRadSaKompanijama);

        jmRadSaMestima.setText("Rad sa mestima");
        jmbGlavniMeni.add(jmRadSaMestima);

        jmRadSaRacunima.setText("Rad sa računima");

        jmiUnosRacuna.setText("Unos računa");
        jmiUnosRacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosRacunaActionPerformed(evt);
            }
        });
        jmRadSaRacunima.add(jmiUnosRacuna);

        jmbGlavniMeni.add(jmRadSaRacunima);

        setJMenuBar(jmbGlavniMeni);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiUnosKompanijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosKompanijeActionPerformed
        FrmUnosKompanije f = new FrmUnosKompanije();
        JDialog d = new JDialog(this, "Unos kompanije", true);
        d.setLayout(new BorderLayout());
        d.add(f, BorderLayout.CENTER);
        d.pack();
        d.setVisible(true);
    }//GEN-LAST:event_jmiUnosKompanijeActionPerformed

    private void jmiPrikazKompanijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrikazKompanijaActionPerformed
        FrmPrikazKompanija f = new FrmPrikazKompanija();
        JDialog d = new JDialog(this, "Prikaz kompanija", true);
        d.setLayout(new BorderLayout());
        d.add(f, BorderLayout.CENTER);
        d.pack();
        d.setVisible(true);

    }//GEN-LAST:event_jmiPrikazKompanijaActionPerformed

    private void jmiPrikazKompanijaModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrikazKompanijaModelActionPerformed
        FrmPrikazKompanijaModel f = new FrmPrikazKompanijaModel();
        JDialog d = new JDialog(this, "Prikaz kompanija", true);
        d.setLayout(new BorderLayout());
        d.add(f, BorderLayout.CENTER);
        d.pack();
        d.setVisible(true);
    }//GEN-LAST:event_jmiPrikazKompanijaModelActionPerformed

    private void jmiUnosRacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosRacunaActionPerformed
        FrmUnosRacuna f = new FrmUnosRacuna();
        JDialog d = new JDialog(this, "Unos računa", true);
        d.setLayout(new BorderLayout());
        d.add(f, BorderLayout.CENTER);
        d.pack();
        d.setVisible(true);    }//GEN-LAST:event_jmiUnosRacunaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGlavna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jmRadSaKompanijama;
    private javax.swing.JMenu jmRadSaMestima;
    private javax.swing.JMenu jmRadSaRacunima;
    private javax.swing.JMenuBar jmbGlavniMeni;
    private javax.swing.JMenuItem jmiPrikazKompanija;
    private javax.swing.JMenuItem jmiPrikazKompanijaModel;
    private javax.swing.JMenuItem jmiUnosKompanije;
    private javax.swing.JMenuItem jmiUnosRacuna;
    // End of variables declaration//GEN-END:variables
}
