/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.kompanija;

import domen.Kompanija;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import komunikacija.Komunikacija;
import transfer.Operacija;
import transfer.TransferObjekatOdgovor;
import transfer.TransferObjekatZahtev;

/**
 *
 * @author Milica
 */
public class FrmPrikazKompanija extends javax.swing.JPanel {

    /**
     * Creates new form FrmPrikazKompanija
     */
    public FrmPrikazKompanija() {
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblKompanije = new javax.swing.JTable();

        jtblKompanije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KompanijaID", "Naziv", "Matični broj", "Ulica", "Broj", "Mestol"
            }
        ));
        jScrollPane1.setViewportView(jtblKompanije);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblKompanije;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        try {
            //List<Kompanija> lk = Kontroler.getInstance().vratiKompanije();
            TransferObjekatZahtev toZahtev = new TransferObjekatZahtev();
            toZahtev.setOperacija(Operacija.VRATI_KOMPANIJE);
            Komunikacija.getInstance().posalji(toZahtev);
            TransferObjekatOdgovor toOdgovor = Komunikacija.getInstance().procitaj();
            List<Kompanija> lk =  (List<Kompanija>) toOdgovor.getRezultat();
            DefaultTableModel model = (DefaultTableModel) jtblKompanije.getModel();
            for (Kompanija k : lk) {
                Object[] red = new Object[6];
                red[0] = k.getKompanijaID();
                red[1] = k.getNaziv();
                red[2] = k.getMaticniBroj();
                red[3] = k.getUlica();
                red[4] = k.getBroj();
                red[5] = k.getMesto();
                // Dodavanje novog reda u tabelu
                model.addRow(red);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
}
