/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.kompanija;

import domen.Kompanija;
import forme.kompanija.model.KompanijaTableModel;
import java.awt.BorderLayout;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import util.Sesija;

/**
 *
 * @author Milica
 */
public class FrmPrikazKompanijaModel extends javax.swing.JPanel {

    /**
     * Creates new form FrmPrikazKompanijaModel
     */
    public FrmPrikazKompanijaModel() {
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblKompanije = new javax.swing.JTable();
        jbtnDetalji = new javax.swing.JButton();
        jbtnDodajRed = new javax.swing.JButton();

        jtblKompanije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblKompanije);

        jbtnDetalji.setText("Detalji");
        jbtnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDetaljiActionPerformed(evt);
            }
        });

        jbtnDodajRed.setText("Dodaj red");
        jbtnDodajRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajRedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jbtnDetalji)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnDodajRed)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDetalji)
                    .addComponent(jbtnDodajRed))
                .addGap(0, 95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDetaljiActionPerformed
        int red = jtblKompanije.getSelectedRow();
        if (red != -1) {
            KompanijaTableModel model = (KompanijaTableModel) jtblKompanije.getModel();
            Kompanija k = model.vratiKompaniju(red);
            // JOptionPane.showMessageDialog(this, k);

            Sesija.getInstance().put("izabrana_kompanija", k);
            SwingUtilities.getWindowAncestor(this).dispose();
            
            FrmUnosKompanije f = new FrmUnosKompanije();
            JDialog d = new JDialog((JDialog)SwingUtilities.getWindowAncestor(this), "Detalji o kompaniji", true);
            d.setLayout(new BorderLayout());
            d.add(f, BorderLayout.CENTER);
            d.pack();
            d.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Odaberite red!");
        }
    }//GEN-LAST:event_jbtnDetaljiActionPerformed

    private void jbtnDodajRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajRedActionPerformed
        KompanijaTableModel model = (KompanijaTableModel) jtblKompanije.getModel();
        model.dodajRed();
    }//GEN-LAST:event_jbtnDodajRedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDetalji;
    private javax.swing.JButton jbtnDodajRed;
    private javax.swing.JTable jtblKompanije;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        try {
            //List<Kompanija> lk = Kontroler.getInstance().vratiKompanije();
            List<Kompanija> lk = new LinkedList<>();
            KompanijaTableModel model = new KompanijaTableModel(lk);
            jtblKompanije.setModel(model);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
}
