/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.kompanija;

import domen.Kompanija;
import domen.Mesto;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import transfer.Operacija;
import transfer.TransferObjekatOdgovor;
import transfer.TransferObjekatZahtev;
import util.Sesija;

/**
 *
 * @author Milica
 */
public class FrmUnosKompanije extends javax.swing.JPanel {

    /**
     * Creates new form FrmUnosKompanije
     */
    public FrmUnosKompanije() {
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtNaziv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtMaticniBroj = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtUlica = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtBroj = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcbMesto = new javax.swing.JComboBox();
        jbtnSacuvaj = new javax.swing.JButton();
        jbtnIzmeni = new javax.swing.JButton();
        jbtnObrisi = new javax.swing.JButton();

        jLabel1.setText("Naziv:");

        jLabel2.setText("Matični broj:");

        jLabel3.setText("Ulica:");

        jLabel4.setText("Broj:");

        jLabel5.setText("Mesto:");

        jcbMesto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbtnSacuvaj.setText("Sačuvaj");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        jbtnIzmeni.setText("Izmeni");

        jbtnObrisi.setText("Obrisi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtNaziv)
                            .addComponent(jtxtMaticniBroj)
                            .addComponent(jtxtUlica)
                            .addComponent(jtxtBroj)
                            .addComponent(jcbMesto, 0, 216, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnSacuvaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnIzmeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnObrisi)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtMaticniBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtUlica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSacuvaj)
                    .addComponent(jbtnIzmeni)
                    .addComponent(jbtnObrisi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        try {
            String naziv = jtxtNaziv.getText().trim();
            String maticniBroj = jtxtMaticniBroj.getText().trim();
            String ulica = jtxtUlica.getText().trim();
            String broj = jtxtBroj.getText().trim();
            Mesto mesto = (Mesto) jcbMesto.getSelectedItem();
            // TODO Valudacija
            Kompanija k = new Kompanija(naziv, maticniBroj, ulica, broj, mesto);
            //Kontroler.getInstance().sacuvajKompaniju(k);
            TransferObjekatZahtev toZahtev = new TransferObjekatZahtev();
            toZahtev.setOperacija(Operacija.SACUVAJ_KOMPANIJU);
            toZahtev.setParametar(k);
            Komunikacija.getInstance().posalji(toZahtev);
            TransferObjekatOdgovor toOdgovor = Komunikacija.getInstance().procitaj();
            if (toOdgovor.getIzuzetak() == null) {
                JOptionPane.showMessageDialog(this, "Kompanija je sacuvana");
            } else {
                throw new Exception(toOdgovor.getIzuzetak());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jbtnSacuvajActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtnIzmeni;
    private javax.swing.JButton jbtnObrisi;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JComboBox jcbMesto;
    private javax.swing.JTextField jtxtBroj;
    private javax.swing.JTextField jtxtMaticniBroj;
    private javax.swing.JTextField jtxtNaziv;
    private javax.swing.JTextField jtxtUlica;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        try {
            //List<Mesto> lm = Kontroler.getInstance().vratiMesta();
            TransferObjekatZahtev toZahtev = new TransferObjekatZahtev();
            toZahtev.setOperacija(Operacija.VRATI_MESTA);
            Komunikacija.getInstance().posalji(toZahtev);
            TransferObjekatOdgovor toOdgovor = Komunikacija.getInstance().procitaj();
            List<Mesto> lm = (List<Mesto>) toOdgovor.getRezultat();
            jcbMesto.removeAllItems();
            for (Mesto m : lm) {
                jcbMesto.addItem(m);
            }
            
            Kompanija k = (Kompanija) Sesija.getInstance().get("izabrana_kompanija");
            if (k != null) {
                // Operacija izmene ili brisanja
                jbtnSacuvaj.setVisible(false);
                jtxtNaziv.setText(k.getNaziv());
                jtxtMaticniBroj.setText(k.getMaticniBroj());
                jtxtUlica.setText(k.getUlica());
                jtxtBroj.setText(k.getBroj());
                jcbMesto.setSelectedItem(k.getMesto());
                Sesija.getInstance().remove("izabrana_kompanija");
            } else {
                // Operacija unosa
                jbtnIzmeni.setVisible(false);
                jbtnObrisi.setVisible(false);
            }
            
            
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
}
